# Generated by Django 4.0.3 on 2022-04-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('charClass', models.CharField(choices=[('war', 'Warrior'), ('arc', 'Archer'), ('mag', 'Mage')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
