# Generated by Django 4.0.3 on 2022-04-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='charClass',
            field=models.CharField(choices=[('Warrior', 'Warrior'), ('Archer', 'Archer'), ('Mage', 'Mage')], max_length=20),
        ),
    ]
