# Generated by Django 4.0.3 on 2022-04-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_character_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='expReq',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='mana',
            field=models.IntegerField(default=50),
        ),
    ]
