# Generated by Django 4.0.3 on 2022-04-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_character_exp_character_expreq_character_health_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('health', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=50)),
            ],
        ),
    ]
