# Generated by Django 4.0.3 on 2022-04-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_monster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='health',
        ),
        migrations.RemoveField(
            model_name='character',
            name='mana',
        ),
    ]
