# Generated by Django 4.0.3 on 2022-04-07 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_character_health_remove_character_mana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['level']},
        ),
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ['level']},
        ),
    ]
