# Generated by Django 4.0.3 on 2022-04-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_character_options_alter_monster_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='expReq',
        ),
        migrations.AddField(
            model_name='monster',
            name='expYield',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monster',
            name='health',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='mana',
            field=models.IntegerField(),
        ),
    ]
