# Generated by Django 4.0.3 on 2022-04-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_character_expreq_monster_expyield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='expReq',
            field=models.IntegerField(default=1000),
        ),
    ]
