# Generated by Django 4.0.3 on 2022-04-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='drops',
            field=models.ManyToManyField(to='main_app.item'),
        ),
    ]
