# Generated by Django 4.0.3 on 2022-04-12 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_monster_drops'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.ManyToManyField(through='main_app.ThroughModel', to='main_app.item'),
        ),
        migrations.AddField(
            model_name='throughmodel',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.character'),
        ),
        migrations.AddField(
            model_name='throughmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.item'),
        ),
    ]
