# Generated by Django 4.0.3 on 2022-04-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_rename_throughmodel_inventory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-level']},
        ),
        migrations.AddField(
            model_name='inventory',
            name='equiped',
            field=models.BooleanField(default=False),
        ),
    ]
