# Generated by Django 4.0.3 on 2022-04-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_character_options_inventory_equiped'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attack',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='mana',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='monster',
            name='attack',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
