# Generated by Django 4.0.3 on 2022-04-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_character_attack_character_health_character_mana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='equipSlot',
            field=models.CharField(choices=[('Armor', 'Armor'), ('Weapon', 'Weapon')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='statAttack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='statHealth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
